---
title: "Code for DC4"
output: html_document
---

This file has code to reproduce our analysis.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(plotly)
library(vroom)
library(igraph)
library(ggraph)
library(grid)
```

```{r load-data}
firewall1 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part1.txt", col_names = FALSE)
firewall2 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part2.txt")
firewall3 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part3.txt", col_names = FALSE)
firewall4 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part4.txt")
firewall_day1 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-04062012.csv")
firewall_day2 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-04072012.csv")
ids_day1 <- vroom::vroom("~/Downloads/dc4-data/IDS/IDS-0406.csv")
ids_day2 <- vroom::vroom("~/Downloads/dc4-data/IDS/IDS-0407.csv")
```

```{r most common firewall sourceIPs day 1}
firewall_day1 <- firewall_day1 %>%
  rename(sourceIP = 'Source IP', 
         destIP = 'Destination IP')

common_firewall_source_1 <- firewall_day1 %>%
  count(sourceIP, sort = TRUE) %>%
  slice(1:25) %>%
  filter(rank(desc(n))>0)
common_firewall_source_1
```

```{r plotting most common source IPs day 1}
common_source_plot_1 <-ggplot(data = common_firewall_source_1, aes(x = reorder(sourceIP, n), y = n)) +
  geom_bar(stat = "identity") + 
  coord_flip() +
  xlab("Common Source IP Addresses") + 
  ylab("Number of Occurances on April 6th")
common_source_plot_1
```

```{r filtering for sourceIP 172.23.0.132}
common_source_172.23.0.132_1 <- firewall_day1 %>%
  filter(sourceIP == '172.23.0.132')
common_source_172.23.0.132_1 
```

```{r destIPs most conected to sourceIP 172.23.0.132 on day 1}
IP_connections_1 <- common_source_172.23.0.132_1 %>%
  count(sourceIP, destIP, sort = TRUE)
IP_connections_1
```

```{r data table to graph connected IPs}
IP_graph_1 <- IP_connections_1 %>%
  group_by(sourceIP) %>%
  filter(n > 50) %>%
  graph_from_data_frame()
IP_graph_1
```

```{r graph indicating how connected IPs are for day 1}
 IP_connect_graph_1 <- ggraph(IP_graph_1, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(IP_graph_1, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void() 
```

```{r most common firewall sourceIPs day 2}
firewall_day2 <- firewall_day2 %>%
  rename(sourceIP = 'Source IP', 
         destIP = 'Destination IP')

common_firewall_source_2 <- firewall_day2 %>%
  count(sourceIP, sort = TRUE) %>%
  slice(1:25) %>%
  filter(rank(desc(n))>0)
common_firewall_source_2
```

```{r filtering for sourceIP 172.23.252.10}
common_source_172.23.252.10 <- firewall_day2 %>%
  filter(sourceIP == '172.23.252.10')
common_source_172.23.252.10
```

```{r destIPs most conected to sourceIP 172.23.0.132 on day 2}
IP_connections_2 <- common_source_172.23.252.10 %>%
  count(sourceIP, destIP, sort = TRUE)
IP_connections_2
```

```{r data table to graph connected IPs}
IP_graph_2 <- IP_connections_2 %>%
  group_by(sourceIP) %>%
  filter(n > 50) %>%
  graph_from_data_frame()
IP_graph_2
```

```{r graph indicating how connected IPs are for day 1}
 IP_connect_graph_2 <- ggraph(IP_graph_2, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(IP_graph_2, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void() 
```

```{r IDS connections}
# change time into datetime type
ids_day1$time <- parse_date_time(ids_day1$time, "%m/%d/%Y %H:%M")
ids_day2$time <- parse_date_time(ids_day2$time, "%m/%d/%Y %H:%M")

# bind datasets together
ids <- rbind(ids_day1, ids_day2)
ids %>%
  group_by(sourcePort, destPort) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

ids %>%
  group_by(destPort, sourcePort) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
ids %>%
  filter(destPort == 445) %>%
  filter(classification == "Attempted Information Leak") %>%
  group_by(sourcePort) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

ids %>%
  select(classification) %>%
  unique()

firewall %>%
  group_by(`Destination port`, `Source port`) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
firewall %>%
  filter(`Destination port` == 80) %>%
  group_by(`Source port`) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```

```{r firewall connections}
# change time into datetime type
firewall_day1$`Date/time` <- parse_date_time(firewall_day1$`Date/time`, "%d/%Om/%Y %H:%M:%S")
firewall_day2$`Date/time` <- parse_date_time(firewall_day2$`Date/time`, "%d/%Om/%Y %H:%M:%S")

# bind datasets together
firewall <- rbind(firewall_day1, firewall_day2)
# change port to numeric
firewall <- firewall %>% mutate(
  `Source port` = as.numeric(`Source port`),
  `Destination port` = as.numeric(`Destination port`)
)

# filter for timeframe to see if something is happening
firewall_subset1 <- firewall %>%
  filter(`Date/time` >= "2012-04-06 00:00:00" & `Date/time` <= "2012-04-06 01:00:00") %>%
  filter(`Destination port` != 80 | `Destination port` != 53)

test <- firewall %>% filter(`Source IP` == "172.23.0.132")
```

```{r privacy violations day1}
#look into IPs that are categorized as potential corporate privacy violation in ids_day1
ids_violations <- ids_day1 %>% 
  filter(classification == "Potential Corporate Privacy Violation")

#look at destination IPs of this classification on day 1 (4/5)
ids_violations %>% 
  group_by(destIP) %>% 
  count(destIP)
```

```{r network graph day1}
#look at source IPs for this classification on day 1
ids_violations %>% 
  group_by(sourceIP) %>% 
  count(destIP)

ids_graph_1 <- ids_violations %>% 
  group_by(sourceIP) %>% 
  count(destIP) %>% 
  graph_from_data_frame()

#create network graph for source ips of potential corporate privacy violations
ids_connect_graph_1 <- ggraph(ids_graph_1, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(ids_graph_1, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "hot pink", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```

```{r privacy violations day2}
#repeating the same process for day 2 of IDS data
ids_violations_2 <- ids_day2 %>% 
  filter(classification == "Potential Corporate Privacy Violation")

ids_violations_2 %>% 
  group_by(destIP) %>% 
  count(destIP)
```

```{r network graph day2}
#look at source IPs for this classification on day 1
ids_violations_2 %>% 
  group_by(sourceIP) %>% 
  count(destIP)

ids_graph_2 <- ids_violations_2 %>% 
  group_by(sourceIP) %>% 
  count(destIP) %>% 
  filter(n > 5) %>% 
  graph_from_data_frame()

#create network graph for source ips of potential corporate privacy violations
ids_connect_graph_2 <- ggraph(ids_graph_2, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(ids_graph_2, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "hot pink", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```
