---
title: "epartakki"
author: "Eleni Partakki"
date: "3/31/2021"
output: html_document
---

```{r}
library(RPostgres)
library(RPostgreSQL)
library(devtools)
library(remotes)
library(DBI)
library(odbc)
```
con <- dbConnect(RPostgres::Postgres())



```{r}
db <- 'database-1'  #provide the name of your db

host_db <- 'database-1.cr7nwtzodfpl.us-east-1.rds.amazonaws.com'

db_port <- '5432'  # or any other port specified by the DBA

db_user <- 'master'  

db_password <- 'password'

con <- dbConnect(RPostgres::Postgres(), dbname = db, host=host_db, port=db_port, user=db_user, password=db_password)  
```




con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "[your driver's name]",
                      Server   = "[your server's path]",
                      Database = "[your database's name]",
                      UID      = rstudioapi::askForPassword("Database user"),
                      PWD      = rstudioapi::askForPassword("Database password"),
                      Port     = 5432)