---
title: "EDA - Marium"
author: "Marium Tapal"
date: "3/24/2021"
output: html_document
---

```{r packages, include=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(here)
library(lubridate)
library(plotly)
library(mosaic)
library(datapasta)
library(patchwork)
library(vroom)
```

```{r}
firewall1 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part1.txt", col_names = FALSE)
firewall2 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part2.txt")
firewall3 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part3.txt", col_names = FALSE)
firewall4 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-part4.txt")
firewall_day1 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-04062012.csv")
firewall_day2 <- vroom::vroom("~/Downloads/dc4-data/Firewall/Firewall-04072012.csv")
ids_day1 <- vroom::vroom("~/Downloads/dc4-data/IDS/IDS-0406.csv")
ids_day2 <- vroom::vroom("~/Downloads/dc4-data/IDS/IDS-0407.csv")
```

# IDS connections

```{r IDS connections}
# change time into datetime type
ids_day1$time <- parse_date_time(ids_day1$time, "%m/%d/%Y %H:%M")
ids_day2$time <- parse_date_time(ids_day2$time, "%m/%d/%Y %H:%M")

# bind datasets together
ids <- rbind(ids_day1, ids_day2)
ids %>%
  group_by(sourcePort, destPort) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

ids %>%
  group_by(destPort, sourcePort) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
ids %>%
  filter(destPort == 445) %>%
  filter(classification == "Attempted Information Leak") %>%
  group_by(sourcePort) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

ids %>%
  select(classification) %>%
  unique()

firewall %>%
  group_by(`Destination port`, `Source port`) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
firewall %>%
  filter(`Destination port` == 80) %>%
  group_by(`Source port`) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
```

# Firewall connections

```{r firewall connections}
# change time into datetime type
firewall_day1$`Date/time` <- parse_date_time(firewall_day1$`Date/time`, "%d/%Om/%Y %H:%M:%S")
firewall_day2$`Date/time` <- parse_date_time(firewall_day2$`Date/time`, "%d/%Om/%Y %H:%M:%S")

# bind datasets together
firewall <- rbind(firewall_day1, firewall_day2)
# change port to numeric
firewall <- firewall %>% mutate(
  `Source port` = as.numeric(`Source port`),
  `Destination port` = as.numeric(`Destination port`)
)

# filter for timeframe to see if something is happening
firewall_subset1 <- firewall %>%
  filter(`Date/time` >= "2012-04-06 00:00:00" & `Date/time` <= "2012-04-06 01:00:00") %>%
  filter(`Destination port` != 80 | `Destination port` != 53)

test <- firewall %>% filter(`Source IP` == "172.23.0.132")
```
